---
title: "Course 9 Week 3 Assignment"
author: "Omer Saeed"
date: "3/7/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
```

## Assignment Details
This assignment uses R Markdown to create a slide presentation that includes a map generated by plotly.<br><br>

I will display US Voter Tournout in 2016 as a heat map by percentage of eligible voters.<br><br>
Data credit: https://ballotpedia.org/Voter_turnout_in_United_States_elections

## Map Using plotly

```{r  echo=FALSE, warning=FALSE}
state_vote = read.csv("/Users/omersaeed/Documents/datascience/coursera/datascience/course9/state_vote.csv")

state_vote$hover <- with(state_vote, paste(State, '<br>', "Voter Turnout: ", Vote, "%"))

borders <- list(color=toRGB("red"))

map_options <- list(
     scope = 'usa',
     projection = list(type = 'albers usa'),
     showlakes = TRUE,
     lakecolor = toRGB("white")
) 

plot_ly(state_vote, z=state_vote$Vote, text = state_vote$hover, locations = state_vote$State, type = "choropleth", locationmode = 'USA-states', color = state_vote$Vote, colors = 'Blues', marker = list(line = borders)) %>% layout(title = 'US Voter Turnout 2016 - Eligible Voters', geo=map_options)

```

